services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    env_file:
      - .secrets/postgres.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
