# This docker-compose is the one used for local development
# It will just simply bring up postgresql running against localhost
# and adminer for database management
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    env_file:
      - env.localhost

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

