# Full production-like docker-compose
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    env_file:
      - .env.prod

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  webapp:
   image: alienmind/phronex-web:latest
   ports:
     - 3000:3000
   extra_hosts:
     - "host.docker.internal:host-gateway"
   env_file:
     - .env.prod
   depends_on:
     - postgres
