# This docker-compose file is only intended for building
# It requires to run first:
#   docker compose -f docker-compose-prebuild.yml up -d
#
# The Docker image builder can access database through internal network (.internal:5432) to run SSR pre-rendering
services:
  webapp:
    image: alienmind/phronex-web:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      extra_hosts:
        - "host.docker.internal:host-gateway"
      network: host
    ports:
      - 3000:3000
    env_file:
      - .env.build
